### ISSUE TITLE
Use Codecov in informational mode

### ISSUE THREAD

**Issue by viniciuschiele** [viniciuschiele/flask-apscheduler#223]
* codecov status check is enabled and it blocks Pull Requests that don't meet a particular coverage threshold.
* By setting the flag `informational` to `true`, the resulting status will pass no matter what the coverage is.
* Codecov settings: https://docs.codecov.com/docs/commit-status
* Upgrade Github step to `codecov/codecov-action@v3`

**Comment by christopherpickering** [comment]
In one of my other repo's I found that having a file `.github/codecov.yaml` with

```yml
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
```

fixes these red checks.

I can start it in a pr sometime.
